name: Deploy Cash Get Backend

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH }}
          script: |
            docker system prune --force
            cd cargle/cash-get-backend
            git checkout deploy
            git pull
            echo "${{ vars.ENVIROMENT_VARIABLES }}" > .env
            docker-compose down
            docker-compose up --build -d
            exit
